apiVersion: v1
kind: Secret
metadata:
  name: {{ include "freeradius.fullname" . }}-envSecrets
  labels:
    {{- include "freeradius.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $k, $v := .Values.environmentVarSecrets }}
  {{ $k }}: {{ $v | b64enc | quote }}
{{- end }}
