apiVersion: v1
kind: Service
metadata:
  name: {{ include "freeradius.fullname" . }}
  labels:
    {{- include "freeradius.labels" . | nindent 4 }}
  annotations:
    metallb.universe.tf/allow-shared-ip: "true"
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: radius-auth
      protocol: UDP
      port: {{ .Values.service.auth_port }}
      targetPort: 1812
    - name: radius-acc
      protocol: UDP
      port: {{ .Values.service.acc_port }}
      targetPort: 1813
      {{ if .Values.exporter.enabled }}
      {{ if ne .Values.service.type "LoadBalancer"}}
    - name: radius-exp
      protocol: TCP
      port: {{ .Values.service.exp_port }}
      targetPort: 9812
      {{ end }}
      {{ end }}
  {{ if eq .Values.service.type "LoadBalancer"}}{{ if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  externalTrafficPolicy: Local
  {{ end }}
  {{ end }}
  selector:
    {{- include "freeradius.selectorLabels" . | nindent 4 }}



